### ISSUE TITLE
Add some cryptic crossword sources

### ISSUE THREAD

**Issue by mikix** [rschroll/crosswords#14]
I'd love it if some cryptic crossword sources were added.

I looked around online, but couldn't find any that published in the .puz format.  :(  Maybe you'll happen upon some in the course of normal crossword searching.

Thanks for considering it!

**Comment by mikix** [comment]
For popular examples of cryptic crosswords, consider:
http://www.theguardian.com/crosswords/series/cryptic
http://puzzles.independent.co.uk/games/cryptic-crossword-independents/
http://www.theglobeandmail.com/puzzles-and-crosswords/cryptic-crossword/

**Comment by rschroll** [comment]
I had looked at the Guardian's puzzles before, but they seem to render 
the puzzle completely on the server side, so we'd have to parse the 
generated HTML to figure out what it looks like.

The Independent and the Globe and Mail are both using the Crossword 
Compiler XML format, so it'd be rather easy to add them to the list of 
sources.  However, cryptic puzzles break the assumption that every cell 
will have both an across clue and a down clue associated with it.

**Comment by rschroll** [comment]
I've added puzzles from the Independent and the Globe and Mail, so I've 
gone ahead and closed this bug.  I'm still happy to add additional 
sources as you find them.  If you figure out a way to extract the grid 
from the Guardian's page, let me know and we can include it as well.

**Comment by mikix** [comment]
Oh thank you so much.  That's great!

**Comment by rschroll** [comment]
I finally figured out where the Guardian was hiding the information about their crosswords, so they are supported now as well.
